---
- hosts: ap-south-1
  remote_user: root
  become: true 

  tasks:
    - name: Install git
      yum:
        name: git
        state: present
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Copy project folder to remote host
      copy:
        src: /home/ashu/React/TodoApp---Firebase/
        dest: /usr/local/Todo
 
    - name: Execute the script
      command: sudo sh /usr/local/Todo/dscript.sh
